services:
  vkanban:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 20
        RUST_VERSION: 1.79
        PNPM_VERSION: 9
    image: vkanban:dev
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - VIBE_KANBAN_ASSET_MODE=prod
      - VIBE_KANBAN_ASSET_DIR=/data
      - GIT_CONFIG_GLOBAL=/data/gitconfig
      # 参考: UID/GID は docker compose 実行元の環境変数から展開されます
      # 例) `UID=$(id -u) GID=$(id -g) make run`
    volumes:
      - ./data:/data
      # Persist worktrees and temp files used by the app (Linux path inside container)
      - ./var_tmp_vkanban:/var/tmp/vibe-kanban
      # Map the host project used during `pnpm dev` into /repos/<org>/<repo>
      #
      # REPO_ABS_PATH: absolute path to your local project root (auto-provided by Makefile)
      # REPO_CANON:     canonical path "<org>/<repo>" (auto-provided by Makefile)
      #
      # Example: /Users/you/src/github.com/you/vkanban -> /repos/you/vkanban
      - ${REPO_ABS_PATH}:/repos/${REPO_CANON}
    restart: always
