services:
  vkanban:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 20
        RUST_VERSION: 1.79
        PNPM_VERSION: 9
        # Provide GitHub base URL to the frontend build so "#123" can link correctly
        # Example: https://github.com/<org>/<repo>
        VITE_REPO_BASE: https://github.com/${REPO_CANON:-kazuph/vkanban}
    image: vkanban:dev
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - VIBE_KANBAN_ASSET_MODE=prod
      # Point Docker to the same DB/config as pnpm dev (macOS App Support)
      - "VIBE_KANBAN_ASSET_DIR=${HOME}/Library/Application Support/ai.bloop.vibe-kanban"
      - GIT_CONFIG_GLOBAL=/data/gitconfig
      # Make container HOME equal to host HOME for consistent repo discovery
      - HOME=${HOME}
      # 参考: UID/GID は docker compose 実行元の環境変数から展開されます
      # 例) `UID=$(id -u) GID=$(id -g) make run`
    volumes:
      - ./data:/data
      # Persist worktrees and temp files used by the app (Linux path inside container)
      - ./var_tmp_vkanban:/var/tmp/vibe-kanban
      # Map the host user's home directory into the same absolute path in the container
      # This allows the server in Docker to access the same project paths that
      # `pnpm dev` (host) sees, e.g. /Users/<you>/... or /home/<you>/...
      - ${HOME}:${HOME}
      # Map the host project used during `pnpm dev` into /repos/<org>/<repo>
      #
      # REPO_ABS_PATH: absolute path to your local project root (auto-provided by Makefile)
      # REPO_CANON:     canonical path "<org>/<repo>" (auto-provided by Makefile)
      #
      # Example: /Users/you/src/github.com/you/vkanban -> /repos/you/vkanban
      # 直接 `docker compose up` する場合に変数未設定でも動くよう、デフォルト値を用意
      # - REPO_ABS_PATH の既定: 現在のリポジトリ直下（この compose.yml のある場所 = `.`）
      # - REPO_CANON の既定: このリポジトリ名に合わせた "kazuph/vkanban"
      - ${REPO_ABS_PATH:-.}:/repos/${REPO_CANON:-kazuph/vkanban}
    restart: always
